Repository MarshallOfSound/electron, pull requests merged in 2018-03, with the labels that each got.

#1 Update .travis.yml
  .travis.yml
Labels: target/1.8.x

#2 Revert "Update .travis.yml"
  .travis.yml
Labels: target/1.8.x

#6 Revert "Revert "Revert "Revert "Revert "Update .travis.yml"""""
  .travis.yml
Labels: target/1.8.x

#7 Revert "Revert "Revert "Revert "Revert "Revert "Update .travis.yml""""""
  .travis.yml
Labels: target/1.8.x

#8 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Update .travis.yml"""""""
  .travis.yml
Labels: target/1.8.x

#9 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Update .travis.yml""""""""
  .travis.yml
Labels: target/1.8.x

#10 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Update .travis.yml"""""""""
  .travis.yml
Labels: target/1.8.x

#11 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Update .travis.yml""""""""""
  .travis.yml
Labels: target/1.8.x

#13 Update README-ko.md
  README-ko.md
Labels: target/1.8.x

#14 Revert "Update README-ko.md"
  README-ko.md
Labels: target/1.8.x

#15 Revert "Revert "Update README-ko.md""
  README-ko.md
Labels: target/1.8.x

#16 Revert "Revert "Revert "Update README-ko.md"""
  README-ko.md
Labels: target/1.8.x

#17 Revert "Revert "Revert "Revert "Update README-ko.md""""
  README-ko.md
Labels: target/1.8.x

#18 Revert "Revert "Revert "Revert "Revert "Update README-ko.md"""""
  README-ko.md
Labels: target/1.8.x

#19 Revert "Revert "Revert "Revert "Revert "Revert "Update README-ko.md""""""
  README-ko.md
Labels: target/1.8.x

#20 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Update README-ko.md"""""""
  README-ko.md
Labels: target/1.8.x

#21 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Update README-ko.md""""""""
  README-ko.md
Labels: target/1.8.x

#22 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Update README-ko.md"""""""""
  README-ko.md
Labels: target/1.8.x

#23 Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Update README-ko.md""""""""""
  README-ko.md
Labels: target/1.8.x

#24 Test
  README.md
  foo
Labels: target/1.8.x

#26 Update README.md
  README.md
Labels: target/1.8.x

#28 Update README.md
  README.md
Labels: target/1.7.x, target/1.8.x

#30 Update README.md
  README.md
Labels: target/1.7.x, target/1.8.x

#31 Update README.md
  README.md
Labels: target/1.7.x, target/1.8.x

#32 Update foo
  foo
Labels: target/1.7.x, target/1.8.x

#34 Update README.md
  README.md
Labels: target/1.7.x, target/1.8.x

#39 Test 1
  bar
  package.json
Labels: target/1.8.x

#41 Test 2
  LICENSE
  thing
Labels: merged/1.8.x

#43 New feature
  feature
Labels: merged/1.8.x

#45 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: target/1.8.x

#46 Revert "Update CODE_OF_CONDUCT.md"
  CODE_OF_CONDUCT.md
Labels: target/1.8.x

#47 Revert "Revert "Update CODE_OF_CONDUCT.md""
  CODE_OF_CONDUCT.md
Labels: target/1.8.x

#48 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: target/1.8.x

#49 Update LICENSE
  LICENSE
Labels: target/1.8.x

#50 Update ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: target/1.8.x

#54 Update README.md
  README.md
Labels: target/1.8.x

#58 Create backported
  backported
Labels: target/1.7.x, target/1.8.x, target/2.0.x

#59 Create new_file_1
  new_file_1
Labels: target/1.7.x, target/1.8.x, target/2.0.x
